решение задач второго модуля
js-tasks-ru/js-20201211_itsanti pull request #2
Opened 2020-12-18 08:32 UTC by itsanti

2020-12-18 08:45 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 02-javascript-data-types/2-pick/index.spec.js — добавлен
- 02-javascript-data-types/3-omit/index.spec.js — добавлен
```

2020-12-18 09:15 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-18 14:49 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    sorted.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-12-18 14:50 UTC, dosandk requested changes
необходимо внести прваки в решение `sortStrings`

2020-12-18 17:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-20 13:19 UTC, dosandk approved these changes

2020-12-20 13:19 UTC, merged